'use strict';
const v037UpdateOverlayEditorOld=updateOverlayEditor;
updateOverlayEditor=function(){v037UpdateOverlayEditorOld();const o=selectedOverlay();if(!o)return;$('overlayFadeIn').value=+o.fadeIn||0;$('overlayFadeOut').value=+o.fadeOut||0;$('overlayAction').value=o.action||'none';$('overlayFadeInLabel').textContent=`${(+o.fadeIn||0).toFixed(1)}초`;$('overlayFadeOutLabel').textContent=`${(+o.fadeOut||0).toFixed(1)}초`;const box=$('overlayTextEditBox'),isText=['text','emoji','sticker'].includes(o.type);box.classList.toggle('hidden',!isText);if(isText){$('overlayTextValue').value=o.text||'';$('overlayTextFont').value=o.font||'Gowun Dodum';$('overlayTextColor').value=o.color||'#ffffff';$('overlayTextBg').value=o.bg&&o.bg!=='transparent'?o.bg:'#000000';$('overlayTextFontWrap').classList.toggle('hidden',o.type!=='text');$('overlayTextColorWrap').classList.toggle('hidden',o.type!=='text');$('overlayTextBgWrap').classList.toggle('hidden',o.type==='emoji');}};
const v037SyncOverlayOld=syncOverlayFromUi;
syncOverlayFromUi=function(){v037SyncOverlayOld();const o=selectedOverlay();if(!o)return;o.fadeIn=clamp(+$('overlayFadeIn').value||0,0,2);o.fadeOut=clamp(+$('overlayFadeOut').value||0,0,2);o.action=$('overlayAction').value||'none';if(['text','emoji','sticker'].includes(o.type)){o.text=$('overlayTextValue').value;o.font=$('overlayTextFont').value||o.font;o.color=$('overlayTextColor').value||o.color;if(o.type!=='emoji')o.bg=$('overlayTextBg').value||o.bg;}$('overlayFadeInLabel').textContent=`${o.fadeIn.toFixed(1)}초`;$('overlayFadeOutLabel').textContent=`${o.fadeOut.toFixed(1)}초`;renderOverlayList();renderFrame(state.currentTime,false);};
const v037OldGestureStart=overlayGestureStart,v037OldGestureMove=overlayGestureMove,v037OldGestureEnd=overlayGestureEnd;
canvas.removeEventListener('pointerdown',v037OldGestureStart);canvas.removeEventListener('pointermove',v037OldGestureMove);canvas.removeEventListener('pointerup',v037OldGestureEnd);canvas.removeEventListener('pointercancel',v037OldGestureEnd);
overlayGestureStart=function(e){if($('overlaySheet').classList.contains('hidden'))return;const p=canvasPoint(e),hs=Math.max(40,canvas.width*.075),active=state.overlays.filter(o=>state.currentTime>=o.start&&state.currentTime<=o.end&&o._drawRect);let o=selectedOverlay();const hit=[...active].reverse().find(x=>{const r=x._drawRect;return p.x>=r.x-hs&&p.x<=r.x+r.w+hs&&p.y>=r.y-hs&&p.y<=r.y+r.h+hs;});if(hit&&hit.id!==state.selectedOverlayId){o=hit;state.selectedOverlayId=o.id;renderOverlayList();updateOverlayEditor();}if(!o||state.currentTime<o.start||state.currentTime>o.end||!o._drawRect)return;const r=o._drawRect,inside=p.x>=r.x-hs&&p.x<=r.x+r.w+hs&&p.y>=r.y-hs&&p.y<=r.y+r.h+hs;if(!inside)return;e.preventDefault();e.stopPropagation();canvas.setPointerCapture?.(e.pointerId);const resize=Math.hypot(p.x-(r.x+r.w),p.y-(r.y+r.h))<=hs*1.5;overlayGesture={id:o.id,mode:resize?'resize':'move',start:p,startX:o.x??.5,startY:o.y??overlayDefaultY(o),startScale:o.scale??.7,baseDist:Math.max(20,Math.hypot(p.x-r.cx,p.y-r.cy))};};
overlayGestureMove=function(e){if(!overlayGesture)return;const o=state.overlays.find(x=>x.id===overlayGesture.id);if(!o)return;const p=canvasPoint(e);e.preventDefault();e.stopPropagation();if(overlayGesture.mode==='move'){o.x=clamp(overlayGesture.startX+(p.x-overlayGesture.start.x)/canvas.width,.02,.98);o.y=clamp(overlayGesture.startY+(p.y-overlayGesture.start.y)/canvas.height,.02,.98);o.position='custom';$('overlayPosition').value='custom';}else{const r=o._drawRect,dist=Math.max(12,Math.hypot(p.x-(r?.cx??canvas.width/2),p.y-(r?.cy??canvas.height/2)));o.scale=clamp(overlayGesture.startScale*(dist/overlayGesture.baseDist),.12,2.2);$('overlayScale').value=Math.round(o.scale*100);$('overlayScaleLabel').textContent=`${Math.round(o.scale*100)}%`;}renderFrame(state.currentTime,false);};
overlayGestureEnd=function(e){if(!overlayGesture)return;try{canvas.releasePointerCapture?.(e?.pointerId);}catch{}pushHistory();overlayGesture=null;updateOverlayEditor();};
canvas.addEventListener('pointerdown',overlayGestureStart);canvas.addEventListener('pointermove',overlayGestureMove);canvas.addEventListener('pointerup',overlayGestureEnd);canvas.addEventListener('pointercancel',overlayGestureEnd);
(function(){const style=document.createElement('style');style.textContent=`#previewCanvas{touch-action:none!important;user-select:none;-webkit-user-select:none;-webkit-touch-callout:none}.v037-overlay-add{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin:8px 0}.v037-overlay-add input{grid-column:1/-1;width:100%;border:1px solid #354154;background:#0a1018;color:#eef1f5;border-radius:10px;padding:10px}.v037-stickers{display:flex;gap:6px;overflow-x:auto;margin:6px 0 10px}.v037-stickers button{min-width:42px;height:40px;font-size:20px;padding:0}.v037-text-edit{border:1px solid #273244;border-radius:10px;padding:8px;margin-bottom:8px;background:#0b1119}.v037-text-edit input[type=text],.v037-text-edit select{width:100%;border:1px solid #354154;background:#0a1018;color:#eef1f5;border-radius:9px;padding:8px}`;document.head.appendChild(style);
const sheet=$('overlaySheet'),sub=sheet?.querySelector('.sheet-sub');if(sheet&&sub){const add=document.createElement('div');add.innerHTML=`<div class="v037-overlay-add"><input id="overlayQuickText" type="text" maxlength="60" placeholder="문구 또는 이모티콘 입력"><button id="addOverlayTextBtn">문구 추가</button><button id="addOverlayEmojiBtn">이모티콘 추가</button></div><div class="v037-stickers"><button data-sticker="⭐">⭐</button><button data-sticker="❤️">❤️</button><button data-sticker="👍">👍</button><button data-sticker="😂">😂</button><button data-sticker="🔥">🔥</button><button data-sticker="✓">✓</button></div>`;sub.parentNode.insertBefore(add,sub.nextSibling);sub.textContent='이미지·영상·문구·이모티콘·스티커를 동시에 겹쳐 쓸 수 있습니다. 미리보기에서 직접 끌어 이동하고 오른쪽 아래 금색 손잡이를 끌어 크기를 조절하세요.';}
const ed=$('overlayEditor');if(ed){const title=ed.querySelector('.control-title');const box=document.createElement('div');box.id='overlayTextEditBox';box.className='v037-text-edit hidden';box.innerHTML=`<label>내용 <input id="overlayTextValue" type="text" maxlength="60"></label><div class="two-col"><label id="overlayTextFontWrap">글꼴<select id="overlayTextFont"><option value="Gowun Dodum">고운돋음</option><option value="Nanum Pen Script">편지지손글씨체</option></select></label><label id="overlayTextColorWrap">글자색<input id="overlayTextColor" type="color" value="#ffffff"></label></div><label id="overlayTextBgWrap">배경 <input id="overlayTextBg" type="color" value="#000000"></label>`;title.insertAdjacentElement('afterend',box);const pos=$('overlayPosition')?.closest('label');const fx=document.createElement('div');fx.className='two-col';fx.innerHTML=`<label>페이드 인 <span id="overlayFadeInLabel">0.2초</span><input id="overlayFadeIn" type="range" min="0" max="2" step="0.1" value="0.2"></label><label>페이드 아웃 <span id="overlayFadeOutLabel">0.2초</span><input id="overlayFadeOut" type="range" min="0" max="2" step="0.1" value="0.2"></label>`;pos?.insertAdjacentElement('beforebegin',fx);const action=document.createElement('label');action.innerHTML=`액션 <select id="overlayAction"><option value="none">없음</option><option value="pop">팝업</option><option value="slide-left">왼쪽에서</option><option value="slide-up">아래에서</option><option value="pulse">펄스</option><option value="shake">흔들기</option></select>`;pos?.insertAdjacentElement('afterend',action);$('overlayScale').max='220';}
const card=$('shortsStyleEnabled')?.closest('.control-card');if(card){card.querySelector('.control-title b').textContent='이 문구의 스타일';const note=card.querySelector('.sheet-sub');if(note)note.textContent='문구마다 따로 저장됩니다. 예: 제목은 뉴스+편지지손글씨, 자막은 일반 자막 스타일.';}
$('addOverlayTextBtn').onclick=()=>v037AddTextOverlay('text',$('overlayQuickText').value);$('addOverlayEmojiBtn').onclick=()=>v037AddTextOverlay('emoji',$('overlayQuickText').value);document.querySelectorAll('[data-sticker]').forEach(b=>b.onclick=()=>v037AddTextOverlay('sticker',b.dataset.sticker));['overlayFadeIn','overlayFadeOut','overlayAction','overlayTextValue','overlayTextFont','overlayTextColor','overlayTextBg'].forEach(id=>{const e=$(id);if(e)e.addEventListener(['overlayFadeIn','overlayFadeOut','overlayTextValue','overlayTextColor','overlayTextBg'].includes(id)?'input':'change',syncOverlayFromUi);});syncShortsStyleUi();renderAll();})();
