'use strict';
const v037OverlayRuntimeOld=overlayRuntime;
overlayRuntime=function(o){if(!['image','video'].includes(o.type)){if(!o.rt)o.rt={};return o.rt;}return v037OverlayRuntimeOld(o);};
function v037OverlayBaseSize(o,src,c2){if(o.type==='image'||o.type==='video'){const sw=src?.videoWidth||src?.naturalWidth||src?.width||0,sh=src?.videoHeight||src?.naturalHeight||src?.height||0;return sw&&sh?{sw,sh}:null;}const text=String(o.text||(o.type==='emoji'?'🙂':'★')),base=o.type==='text'?64:o.type==='emoji'?112:104;c2.save();c2.font=`700 ${base}px ${o.type==='text'?fontStack(o.font||'Gowun Dodum'):'system-ui,sans-serif'}`;const sw=Math.max(base*1.15,c2.measureText(text).width+(o.type==='text'?42:28));c2.restore();return{sw,sh:base*1.38};}
overlayRect=function(o,src,c2=ctx){const sz=v037OverlayBaseSize(o,src,c2);if(!sz)return null;let s;if(o.type==='image'||o.type==='video')s=Math.min(canvas.width/sz.sw,canvas.height/sz.sh)*clamp(o.scale??.7,.12,2.2);else s=Math.min(1,canvas.width/(sz.sw*1.15))*clamp(o.scale??.7,.18,2.2);const w=sz.sw*s,h=sz.sh*s,cx=clamp(o.x??.5,.02,.98)*canvas.width,cy=clamp(o.y??overlayDefaultY(o),.02,.98)*canvas.height;return{x:cx-w/2,y:cy-h/2,w,h,cx,cy};};
function v037OverlayAlpha(o,g){let a=clamp(o.opacity??1,0,1),dur=Math.max(.05,o.end-o.start),fi=clamp(+o.fadeIn||0,0,dur),fo=clamp(+o.fadeOut||0,0,dur);if(fi)a*=clamp((g-o.start)/fi,0,1);if(fo)a*=clamp((o.end-g)/fo,0,1);return a;}
function v037OverlayMotion(o,g){const dur=Math.max(.05,o.end-o.start),p=clamp((g-o.start)/dur,0,1),enter=clamp((g-o.start)/Math.min(.45,dur*.35),0,1);let dx=0,dy=0,scale=1,rot=0;switch(o.action||'none'){case'pop':scale=.55+.45*enter;break;case'slide-left':dx=(1-enter)*-canvas.width*.28;break;case'slide-up':dy=(1-enter)*canvas.height*.18;break;case'pulse':scale=1+.07*Math.sin(p*Math.PI*6);break;case'shake':dx=Math.sin(p*Math.PI*12)*canvas.width*.012;rot=Math.sin(p*Math.PI*10)*.025;break;}return{dx,dy,scale,rot};}
function v037DrawOverlayContent(c2,o,src,r){if(o.type==='image'||o.type==='video'){c2.drawImage(src,r.x,r.y,r.w,r.h);return;}const text=String(o.text||'');if(o.type==='text'){const fs=Math.max(18,r.h*.54);c2.font=`700 ${fs}px ${fontStack(o.font||'Gowun Dodum')}`;c2.textAlign='center';c2.textBaseline='middle';if(o.bg&&o.bg!=='transparent'){c2.fillStyle=hexAlpha(o.bg,.68);roundRect(c2,r.x,r.y,r.w,r.h,Math.max(12,r.h*.16));c2.fill();}c2.lineWidth=Math.max(2,fs*.07);c2.strokeStyle='rgba(0,0,0,.62)';c2.strokeText(text,r.cx,r.cy);c2.fillStyle=o.color||'#fff';c2.fillText(text,r.cx,r.cy);return;}const fs=Math.max(24,r.h*.72);c2.font=`700 ${fs}px system-ui,sans-serif`;c2.textAlign='center';c2.textBaseline='middle';if(o.type==='sticker'){c2.fillStyle=hexAlpha(o.bg||'#ffffff',.9);roundRect(c2,r.x,r.y,r.w,r.h,Math.max(14,r.h*.28));c2.fill();c2.strokeStyle='rgba(0,0,0,.22)';c2.lineWidth=Math.max(2,r.h*.025);c2.stroke();}c2.fillStyle=o.color||'#fff';c2.fillText(text||'★',r.cx,r.cy);}
drawOverlayOne=function(c2,o,src,g=state.currentTime){const base=overlayRect(o,src,c2);if(!base)return;const m=v037OverlayMotion(o,g),w=base.w*m.scale,h=base.h*m.scale,cx=base.cx+m.dx,cy=base.cy+m.dy,r={x:cx-w/2,y:cy-h/2,w,h,cx,cy};c2.save();c2.globalAlpha=v037OverlayAlpha(o,g);if(m.rot){c2.translate(cx,cy);c2.rotate(m.rot);v037DrawOverlayContent(c2,o,src,{x:-w/2,y:-h/2,w,h,cx:0,cy:0});}else v037DrawOverlayContent(c2,o,src,r);c2.restore();o._drawRect=r;if(o.id===state.selectedOverlayId&&!state.exporting&&!$('overlaySheet').classList.contains('hidden')){c2.save();c2.strokeStyle='rgba(255,198,94,.98)';c2.lineWidth=Math.max(3,canvas.width*.005);c2.setLineDash([10,7]);c2.strokeRect(r.x,r.y,r.w,r.h);c2.setLineDash([]);const hs=Math.max(24,canvas.width*.045);c2.fillStyle='#f0b85e';c2.fillRect(r.x+r.w-hs/2,r.y+r.h-hs/2,hs,hs);c2.restore();}};
drawOverlays=function(c2,g,forPlay=false){state.overlays.forEach(o=>{if(g<o.start||g>o.end)return;let src=null;if(o.type==='video'){const rt=overlayRuntime(o),v=rt.el,dur=Number.isFinite(v.duration)&&v.duration>0?v.duration:Math.max(.1,o.end-o.start),target=(g-o.start)%dur;if(!forPlay&&Math.abs((v.currentTime||0)-target)>.05)try{v.currentTime=target}catch{}if(forPlay){if(Math.abs((v.currentTime||0)-target)>.4)try{v.currentTime=target}catch{}if(v.paused){const q=v.play();q?.catch?.(()=>{});}}else v.pause();src=v;}else if(o.type==='image')src=overlayRuntime(o).img;drawOverlayOne(c2,o,src,g);});};
function v037OverlayBase(type,name,start,end){return{id:uid('ov'),type,file:null,url:null,name,start,end:Math.max(start+.1,end),scale:type==='text'?.8:.7,opacity:1,position:'center',x:.5,y:.5,fadeIn:.2,fadeOut:.2,action:'none',font:'Gowun Dodum',color:'#ffffff',bg:type==='sticker'?'#ffffff':'#000000',text:'',rt:null};}
const v037AddOverlayFileOld=addOverlayFile;
addOverlayFile=async function(file){if(!file)return;const before=state.overlays.length;await v037AddOverlayFileOld(file);const o=state.overlays.at(-1);if(state.overlays.length>before&&o){o.fadeIn=.2;o.fadeOut=.2;o.action='none';o.x=.5;o.y=.5;v037SelectOverlay(o.id);}};
function v037AddTextOverlay(type,text){text=String(text||'').trim();if(!text)return toast(type==='emoji'?'이모티콘을 입력해 주세요.':'내용을 입력해 주세요.');pushHistory();const start=clamp(state.currentTime,0,totalDuration()||999),end=Math.min(totalDuration()||start+3,start+3),label={text:'문구',emoji:'이모티콘',sticker:'스티커'}[type],o=v037OverlayBase(type,`${label} · ${text.slice(0,12)}`,start,end);o.text=text;if(type==='emoji'){o.scale=.6;o.bg='transparent';}if(type==='sticker'){o.scale=.65;o.bg='#ffffff';}state.overlays.push(o);state.selectedOverlayId=o.id;v037SelectOverlay(o.id);toast(`${label} 오버레이를 추가했습니다.`);}
function v037SelectOverlay(id){state.selectedOverlayId=id;const o=selectedOverlay();if(o&&(state.currentTime<o.start||state.currentTime>o.end))state.currentTime=Math.min(o.end-.01,o.start+.01);renderOverlayList();updateOverlayEditor();renderFrame(state.currentTime,false);}
renderOverlayList=function(){const g=$('overlayList');if(!g)return;g.innerHTML='';state.overlays.forEach(o=>{const d=document.createElement('div');d.className=`text-item${o.id===state.selectedOverlayId?' selected-item':''}`;const lab={image:'이미지',video:'영상',text:'문구',emoji:'이모티콘',sticker:'스티커'}[o.type]||'오버레이';d.innerHTML=`<b>${lab} · ${escapeHtml(o.text||o.name)}</b><span>${o.start.toFixed(1)}~${o.end.toFixed(1)}</span>`;d.onclick=()=>v037SelectOverlay(o.id);g.appendChild(d);});};
