'use strict';
let v037TextPreset='premium';
const v037OldDraft=draftTextFromUi;
draftTextFromUi=function(){const d=v037OldDraft();if(!d)return d;d.styleMode=$('shortsStyleEnabled')?.checked?'shorts':'caption';d.shortsPreset=v037TextPreset;return d;};
function v037DrawTextItem(c2,t){if(!t)return;if(t.styleMode==='shorts'){const pr=SHORTS_STYLE_PRESETS[t.shortsPreset]||SHORTS_STYLE_PRESETS.premium;const pos=t.kind==='title'?'top':'bottom';paintStyleBand(c2,t.text,panelWithTextStyle(pos==='top'?pr.top:pr.bottom,t),pos);}else drawPlainText(c2,t);}
drawTexts=function(c2,g){const draft=draftTextFromUi();state.texts.filter(t=>t.id!==state.selectedTextId&&g>=t.start&&g<=t.end).forEach(t=>v037DrawTextItem(c2,t));if(draft)v037DrawTextItem(c2,draft);};
syncShortsStyleUi=function(){const t=selectedText();if(t){v037TextPreset=t.shortsPreset||'premium';$('shortsStyleEnabled').checked=t.styleMode==='shorts';}document.querySelectorAll('#shortsStylePresets [data-style]').forEach(b=>b.classList.toggle('active',b.dataset.style===v037TextPreset));const row=$('shortsStylePresets');if(row)row.style.opacity=$('shortsStyleEnabled').checked?'1':'.45';};
applyShortsStyle=function(id){v037TextPreset=id;$('shortsStyleEnabled').checked=true;syncShortsStyleUi();renderFrame(state.currentTime,false);};
resetTextEditor=function(){state.selectedTextId=null;$('textInput').value='';$('shortsStyleEnabled').checked=false;v037TextPreset='premium';$('addTextBtn').textContent='문구 추가';renderTextList();syncShortsStyleUi();renderFrame(state.currentTime,false);};
loadTextToEditor=function(t){if(!t)return;state.selectedTextId=t.id;$('textInput').value=t.text;$('textKind').value=t.kind||'caption';$('textFont').value=t.font||'Gowun Dodum';$('textSize').value=+t.size||52;$('textPosition').value=t.position||'bottom';$('textColor').value=t.color||'#ffffff';$('textBg').value=t.bg||'#000000';$('textStart').value=(+t.start||0).toFixed(1);$('textEnd').value=(+t.end||(+t.start||0)+3).toFixed(1);$('shortsStyleEnabled').checked=t.styleMode==='shorts';v037TextPreset=t.shortsPreset||'premium';$('addTextBtn').textContent='문구 수정 저장';renderTextList();syncShortsStyleUi();renderFrame(state.currentTime,false);};
addText=function(){const text=$('textInput').value.trim();if(!text)return toast('문구를 입력해 주세요.');const start=clamp(+$('textStart').value||0,0,totalDuration()||999),end=Math.max(start+.1,+$('textEnd').value||start+3),kind=$('textKind').value,font=$('textFont').value;const data={text,start,end:clamp(end,0,totalDuration()||end),kind,font,size:+$('textSize').value||52,position:$('textPosition').value,color:$('textColor').value,bg:$('textBg').value,styleMode:$('shortsStyleEnabled').checked?'shorts':'caption',shortsPreset:v037TextPreset};pushHistory();const old=selectedText();if(old)Object.assign(old,data);else state.texts.push({id:uid('text'),...data});resetTextEditor();toast(old?'문구를 수정했습니다.':'문구를 추가했습니다.');};
renderTextList=function(){const g=$('textList');g.innerHTML='';state.texts.forEach(t=>{const d=document.createElement('div');d.className=`text-item${t.id===state.selectedTextId?' selected-item':''}`;const st=t.styleMode==='shorts'?`쇼츠 · ${(SHORTS_STYLE_PRESETS[t.shortsPreset]||SHORTS_STYLE_PRESETS.premium).name}`:'자막 스타일';d.innerHTML=`<b>${escapeHtml(t.text)}</b><span>${st} · ${t.start.toFixed(1)}~${t.end.toFixed(1)}</span>`;d.onclick=()=>loadTextToEditor(t);const x=document.createElement('button');x.textContent='삭제';x.className='danger';x.onclick=e=>{e.stopPropagation();pushHistory();state.texts=state.texts.filter(v=>v.id!==t.id);if(state.selectedTextId===t.id)resetTextEditor();else{renderTextList();renderFrame(state.currentTime,false);}};d.appendChild(x);g.appendChild(d);});};
const v037CreateVideoRuntime=createVideoRuntime;
createVideoRuntime=function(c){const rt=v037CreateVideoRuntime(c);if(rt?.el){rt.el.muted=false;rt.el.defaultMuted=false;if(rt.gain)rt.el.volume=1;}return rt;};
connectClipAudio=function(c){if(c.type!=='video'||!c.rt?.el||!state.audioCtx||c.rt.source)return;try{c.rt.el.muted=false;c.rt.el.defaultMuted=false;c.rt.el.volume=1;const source=state.audioCtx.createMediaElementSource(c.rt.el),gain=state.audioCtx.createGain();source.connect(gain);gain.connect(state.audioDest);gain.connect(state.audioCtx.destination);c.rt.source=source;c.rt.gain=gain;}catch(e){console.warn('clip audio connect failed',e);}};
setGain=function(c,g){if(!c||c.type!=='video')return;const level=clamp(g*(c.volume??1),0,1),v=c.rt?.el;if(v){v.muted=false;v.defaultMuted=false;}if(c.rt?.gain){if(v)v.volume=1;c.rt.gain.gain.value=level;}else if(v)v.volume=level;};
const v037AddFiles=addFiles;
addFiles=async function(files){await v037AddFiles(files);if(state.audioCtx)state.clips.forEach(connectClipAudio);state.clips.forEach(c=>{if(c.type==='video'&&c.volume==null)c.volume=1;});};
