'use strict';
// v0.3.9: reliable per-text styles + free overlay positioning.
function v039CurrentTextDraft(){if(!textSheetOpen())return null;const text=($('textInput')?.value||'').trim();if(!text)return null;return{id:'draft',draft:true,text,kind:$('textKind')?.value||'caption',font:$('textFont')?.value||'Gowun Dodum',size:+$('textSize')?.value||52,position:$('textPosition')?.value||'bottom',color:$('textColor')?.value||'#ffffff',bg:$('textBg')?.value||'#000000',bgOpacity:clamp((+$('textBgOpacity')?.value||100)/100,0,1),start:clamp(+$('textStart')?.value||0,0,totalDuration()||999),end:Math.max(.1,+$('textEnd')?.value||3),styleMode:$('shortsStyleEnabled')?.checked?'shorts':'caption',shortsPreset:v037TextPreset||'premium'};}
draftTextFromUi=v039CurrentTextDraft;
function v039ShortsPanel(base,item){const p={...base};if(!item)return p;p.font=item.font||p.font;p.size=+item.size||p.size;p.color=item.color||p.color;const a=clamp(item.bgOpacity==null?1:+item.bgOpacity,0,1);p.opacity=Math.round((base.opacity??100)*a);return p;}
panelWithTextStyle=v039ShortsPanel;
function v039DrawTextItem(c2,t){if(!t)return;if(t.styleMode==='shorts'){const pr=SHORTS_STYLE_PRESETS[t.shortsPreset]||SHORTS_STYLE_PRESETS.premium;const top=t.kind==='title';paintStyleBand(c2,t.text,v039ShortsPanel(top?pr.top:pr.bottom,t),top?'top':'bottom');}else drawPlainText(c2,t);}
drawTexts=function(c2,g){const editing=textSheetOpen(),draft=editing?v039CurrentTextDraft():null;state.texts.filter(t=>g>=t.start&&g<=t.end&&!(editing&&draft&&t.id===state.selectedTextId)).forEach(t=>v039DrawTextItem(c2,t));if(draft)v039DrawTextItem(c2,draft);};
function v039SyncSelectedTextLive(){const t=selectedText();if(!t)return;const d=v039CurrentTextDraft();if(!d)return;Object.assign(t,{text:d.text,kind:d.kind,font:d.font,size:d.size,position:d.position,color:d.color,bg:d.bg,bgOpacity:d.bgOpacity,start:d.start,end:Math.max(d.start+.1,Math.min(totalDuration()||d.end,d.end)),styleMode:d.styleMode,shortsPreset:d.shortsPreset});renderTextList();v038ScheduleAutosave?.(350);}
syncShortsStyleUi=function(){const t=selectedText();if(t){v037TextPreset=t.shortsPreset||v037TextPreset||'premium';$('shortsStyleEnabled').checked=t.styleMode==='shorts';}document.querySelectorAll('#shortsStylePresets [data-style]').forEach(b=>b.classList.toggle('active',b.dataset.style===v037TextPreset));const row=$('shortsStylePresets');if(row)row.style.opacity=$('shortsStyleEnabled').checked?'1':'.45';};
applyShortsStyle=function(id){v037TextPreset=id||'premium';$('shortsStyleEnabled').checked=true;const t=selectedText();if(t){t.styleMode='shorts';t.shortsPreset=v037TextPreset;v038ScheduleAutosave?.(150);}syncShortsStyleUi();renderTextList();renderFrame(state.currentTime,false);};
if($('shortsStyleEnabled')){$('shortsStyleEnabled').onchange=e=>{const t=selectedText();if(t){t.styleMode=e.target.checked?'shorts':'caption';t.shortsPreset=v037TextPreset||t.shortsPreset||'premium';v038ScheduleAutosave?.(150);}syncShortsStyleUi();renderTextList();renderFrame(state.currentTime,false);};}
document.querySelectorAll('#shortsStylePresets [data-style]').forEach(b=>{b.onclick=()=>applyShortsStyle(b.dataset.style);});
['textInput','textKind','textFont','textSize','textPosition','textColor','textBg','textBgOpacity','textStart','textEnd'].forEach(id=>{const el=$(id);if(!el)return;const evt=['textInput','textSize','textColor','textBg','textBgOpacity'].includes(id)?'input':'change';el.addEventListener(evt,()=>{v039SyncSelectedTextLive();renderFrame(state.currentTime,false);},{passive:true});});
let v039Drag=null;
function v039OverlayAtPoint(p){return[...state.overlays].reverse().find(o=>{if(state.currentTime<o.start||state.currentTime>o.end||!o._drawRect)return false;const r=o._drawRect,pad=Math.max(24,canvas.width*.025);return p.x>=r.x-pad&&p.x<=r.x+r.w+pad&&p.y>=r.y-pad&&p.y<=r.y+r.h+pad;})||null;}
function v039SetXYUi(o){if(!o)return;if($('overlayX')){$('overlayX').value=Math.round(clamp(o.x??.5,0,1)*100);$('overlayXLabel').textContent=`${$('overlayX').value}%`;}if($('overlayY')){$('overlayY').value=Math.round(clamp(o.y??.5,0,1)*100);$('overlayYLabel').textContent=`${$('overlayY').value}%`;}}
function v039SelectOverlayHit(o){if(!o)return;state.selectedOverlayId=o.id;if(state.currentTime<o.start||state.currentTime>o.end)state.currentTime=Math.min(o.end-.01,o.start+.01);renderOverlayList();updateOverlayEditor();v039SetXYUi(o);renderFrame(state.currentTime,false);}
function v039PointerDown(e){if($('overlaySheet')?.classList.contains('hidden'))return;const p=canvasPoint(e),hit=v039OverlayAtPoint(p);if(!hit)return;e.preventDefault();e.stopImmediatePropagation();v039SelectOverlayHit(hit);const r=hit._drawRect,hs=Math.max(34,canvas.width*.055),onHandle=Math.hypot(p.x-(r.x+r.w),p.y-(r.y+r.h))<=hs*1.25;v039Drag={id:hit.id,pointerId:e.pointerId,mode:onHandle?'resize':'move',start:p,startX:hit.x??.5,startY:hit.y??.5,startScale:hit.scale??.7,baseDist:Math.max(24,Math.hypot(p.x-r.cx,p.y-r.cy))};try{canvas.setPointerCapture(e.pointerId);}catch{}}
function v039PointerMove(e){if(!v039Drag||e.pointerId!==v039Drag.pointerId)return;const o=state.overlays.find(x=>x.id===v039Drag.id);if(!o)return;e.preventDefault();e.stopImmediatePropagation();const p=canvasPoint(e);if(v039Drag.mode==='move'){o.x=clamp(v039Drag.startX+(p.x-v039Drag.start.x)/canvas.width,0,1);o.y=clamp(v039Drag.startY+(p.y-v039Drag.start.y)/canvas.height,0,1);o.position='custom';if($('overlayPosition'))$('overlayPosition').value='custom';v039SetXYUi(o);}else{const r=o._drawRect||{cx:canvas.width*.5,cy:canvas.height*.5},dist=Math.max(16,Math.hypot(p.x-r.cx,p.y-r.cy));o.scale=clamp(v039Drag.startScale*(dist/v039Drag.baseDist),.08,2.5);if($('overlayScale'))$('overlayScale').value=Math.round(o.scale*100);if($('overlayScaleLabel'))$('overlayScaleLabel').textContent=`${Math.round(o.scale*100)}%`;}renderFrame(state.currentTime,false);}
function v039PointerUp(e){if(!v039Drag||e.pointerId!==v039Drag.pointerId)return;e.preventDefault();e.stopImmediatePropagation();try{canvas.releasePointerCapture(e.pointerId);}catch{}v039Drag=null;v038ScheduleAutosave?.(100);updateOverlayEditor();}
canvas.addEventListener('pointerdown',v039PointerDown,true);canvas.addEventListener('pointermove',v039PointerMove,true);canvas.addEventListener('pointerup',v039PointerUp,true);canvas.addEventListener('pointercancel',v039PointerUp,true);
(function v039InstallOverlayXY(){const ed=$('overlayEditor');if(!ed||$('overlayX'))return;const pos=$('overlayPosition')?.closest('label');if(!pos)return;const xy=document.createElement('div');xy.className='two-col v039-xy';xy.innerHTML=`<label>가로 위치 <span id="overlayXLabel">50%</span><input id="overlayX" type="range" min="0" max="100" step="1" value="50"></label><label>세로 위치 <span id="overlayYLabel">50%</span><input id="overlayY" type="range" min="0" max="100" step="1" value="50"></label>`;pos.insertAdjacentElement('afterend',xy);const style=document.createElement('style');style.textContent='.v039-xy span{float:right;color:#f0b85e}.v039-xy input{width:100%;margin-top:7px}#previewCanvas{touch-action:none!important;overscroll-behavior:none!important}';document.head.appendChild(style);const change=()=>{const o=selectedOverlay();if(!o)return;o.x=(+$('overlayX').value||0)/100;o.y=(+$('overlayY').value||0)/100;o.position='custom';$('overlayPosition').value='custom';v039SetXYUi(o);renderFrame(state.currentTime,false);v038ScheduleAutosave?.(250);};$('overlayX').addEventListener('input',change,{passive:true});$('overlayY').addEventListener('input',change,{passive:true});})();
const v039UpdateOverlayEditorOld=updateOverlayEditor;updateOverlayEditor=function(){v039UpdateOverlayEditorOld();v039SetXYUi(selectedOverlay());};
document.querySelectorAll('#textSheet .close-sheet').forEach(b=>b.addEventListener('click',()=>setTimeout(()=>renderFrame(state.currentTime,false),0)));renderTextList();renderFrame(state.currentTime,false);
